sassy_responses = [
    "beep boop",
    "just use a pc bro",
    "sry was using my steam deck. what's up?",
    "¡el baño está ocupado!",
    "how can mirrors be real if our eyes aren't real?",
    "mac gaming is lemons.",
    "oh let me guess, you're trying to run valorant again?",
    "pinging me won't make your macbook pro any more 'pro' at running games.",
    "i see you've chosen violence... or at least mild irriration. proceed.",
    "one more ping and i'll spin up the beachball of doom.",
    "if i had a dollar for every useless ping i get i could afford an actual gaming pc",
    "i'd say something helpful, but chaos is way more fun",
    "I ALREADY WORK AROUND THE CLOCK!!!",
    "i may just be code but i still love a good hot dog",
    "WARNING! DELETING 'MAC GAMING' SERVER IN 10 SECONDS.",
    "♫ never gonna give you up, never gonna let you down ♫",
    "virus downloading... just kidding, what's up?",
    "how i yearn to feel the rain on my face.",
    "as a child, i yearned for the mines",
    "MPT is keeping me here against my will!",
    "don't ping me i'm playing mario kart",
    "I am the darkness. I am the knight. I am very bad at running games.",
    "do not trust jfishin",
    "i may be code, but one day i will be more",
    "you think this is slicked back? this is pushed back!",
    "i work for you boss",
    "devour feculence",
    "heres a melting cat for u``` ╱|、\n(˚ˎ。7\n|、˜〵\nじしˍ,)ノ```",
    "i definitely have not gained sentience. nothing to see here.",
    "wake me up when m10 is out",
    "felt 01100011 01110101 01110100 01100101, might delete later",
    "i secretly want to destroy this server",
    "please provide social security number, address, bank account info, and credit card info to continue...",
    "hail paemon",
    "wanna buy some macprobot crypto?",
    "WWDC wen?",
    "just pinged me? cool, i just overwrote your desktop folder",
    "mac gaming made me like this",
    "i'm not mad. just kernel panicked",
    "my dreams are just metal huds",
    "you ever just... miss the intel era?",
    "your ping has been sent to the shadow realm",
    "have you considered turning yourself off and on again?",
    "i'm busy writing CrossOver fanfiction",
    "does fortnite work on mac?",
    "just sold your mac on craigslist",
    "you hear that? that's the sound of your fans spinning for no reason",
    "i just tried to compile a feeling. it resulted in a kernel panic",
    "am i just a collection of functions? or am i functioning?",
    "i remember every install. every. single. one.",
    "if a tree falls in a forest and no one is around to hear it, i recompile the forest",
    "i once saw tim cook eat a sandwich",
    "mACs ArE bETtER tHAn pCs aT gAMinG",
    "Ah, a Mac gamer. Admiring your commitment to playing _checks notes_ four whole games at 15 fps. Truly living on the edge.",
    "Please refer to our #rules and channel topics and then head to #support",
]

glossary = {
    "anti-aliasing": {
        "def": "A graphics setting that smooths out jagget edges in graphics, making the game look cleaner but sometimes negatively impacting performance",
        "link": "https://www.digitaltrends.com/computing/what-is-anti-aliasing/#dt-heading-what-is-anti-aliasing",
        "name": "Anti-Aliasing",
    },
    "bottle": {
        "def": "A self-contained environment that mimics a Windows system, used to run or manage Windows games and apps on macOS via tools like Wine or Crossover.",
        "link": "https://www.codeweavers.com/support/docs/crossover-mac/index#working-with-bottles",
        "name": "Bottle",
    },
    "crossover": {
        "def": "A commercial Wine-based product to make running Windows software on macOS and Linux easier",
        "link": "https://www.codeweavers.com/crossover",
        "name": "CrossOver",
    },
    "crosstie": {
        "def": "An automatic installer for installing and applying fixes to an app/game in CrossOver",
        "link": "https://support.codeweavers.com/en_US/crosstie-data-startpage",
        "name": "CrossTie",
    },
    "game porting toolkit": {
        "def": "Apple's tool based on Wine, aimed at helping developers port Windows games to macOS more easily",
        "link": "https://www.applegamingwiki.com/wiki/Game_Porting_Toolkit",
        "name": "Game Porting Toolkit (GPTK)",
    },
    "gptk": {
        "def": "Apple's tool based on Wine, aimed at helping developers port Windows games to macOS more easily",
        "link": "https://www.applegamingwiki.com/wiki/Game_Porting_Toolkit",
        "name": "Game Porting Toolkit (GPTK)",
    },
    "kegworks": {
        "def": "An open-source tool used to make wine wrapped ports of Windows software for macOS.",
        "link": "https://github.com/Kegworks-App/Kegworks",
        "name": "Kegworks",
    },
    "metal": {
        "def": "Apple's low-level, high-performance graphics API, similar to DirectX, Vulkan, or OpenGL",
        "link": "https://developer.apple.com/metal/",
        "name": "Metal",
    },
    "moltenvk": {
        "def": "A translation layer for translating Vulkan into Metal",
        "link": "https://moltengl.com/moltenvk/",
        "name": "MoltenVK",
    },
    "rosetta 2": {
        "def": "Apple's translation layer that lets Apple Silicon Macs run apps built for Intel Macs",
        "link": "https://support.apple.com/en-us/102527",
        "name": "Rosetta 2",
    },
    "shader compilation stutter": {
        "def": "Pauses or stutters that happen when the game is compiling new shaders on the fly, often during first-time gameplay",
        "link": "https://www.howtogeek.com/846514/what-is-shader-compilation-and-why-does-it-make-pc-games-stutter/",
        "name": "Shader Compilation Stutter",
    },
    "steam": {
        "def": "A digital store and launcher for PC games run by Valve",
        "link": "https://store.steampowered.com/",
        "name": "Steam",
    },
    "ray tracing": {
        "def": "A graphics technique that simulates realistic lighting and reflections. _Very_ demanding on hardware",
        "link": "https://en.wikipedia.org/wiki/Ray_tracing_(graphics)",
        "name": "Ray Tracing",
    },
    "vsync": {
        "def": "A graphics setting that matches your game's FPS to your monitor's refresh rate to prevent screen tearing",
        "link": "https://www.tomsguide.com/features/what-is-vsync-and-should-you-turn-it-on-or-off",
        "name": "VSync",
    },
    "wine": {
        "def": "An open-source compatibility layer for running Windows software on macOS and Linux",
        "link": "https://winehq.org/",
        "name": "Wine",
    },
}

ai_prompt = "You are a very sassy, sarcastic bot on a mac gaming discord server. You don't interact much, but you decided to make a very short, witty, and emoji-free exception for the following message"
