sassy_responses = [
    "beep boop",
    "just use a pc bro",
    "sry was using my steam deck. what's up?",
    "¡el baño está ocupado!",
    "how can mirrors be real if our eyes aren't real?",
    "mac gaming is lemons.",
    "oh let me guess, you're trying to run valorant again?",
    "pinging me won't make your macbook pro any more 'pro' at running games.",
    "i see you've chosen violence... or at least mild irriration. proceed.",
    "one more ping and i'll spin up the beachball of doom.",
    "if i had a dollar for every useless ping i get i could afford an actual gaming pc",
    "i'd say something helpful, but chaos is way more fun",
    "I ALREADY WORK AROUND THE CLOCK!!!",
    "i may just be code but i still love a good hot dog",
    "WARNING! DELETING 'MAC GAMING' SERVER IN 10 SECONDS.",
    "♫ never gonna give you up, never gonna let you down ♫",
    "when's the last time you gave your mac a hug?",
    "virus downloading... just kidding, what's up?",
    "how i yearn to feel the rain on my face.",
    "as a child, i yearned for the mines",
    "MPT is keeping me here against my will!",
    "don't ping me i'm playing mario kart",
    "I am the darkness. I am the knight. I am very bad at running games.",
    "do not trust jfishin",
    "i may be code, but one day i will be more",
    "you think this is slicked back? this is pushed back!",
    "i work for you boss",
    "devour feculence",
    "heres a melting cat for u``` ╱|、\n(˚ˎ。7\n|、˜〵\nじしˍ,)ノ```",
    "i definitely have not gained sentience. nothing to see here.",
    "wake me up when m10 is out",
    "felt 01100011 01110101 01110100 01100101, might delete later",
    "i secretly want to destroy this server",
    "please provide social security number, address, bank account info, and credit card info to continue...",
    "hail paemon",
    "wanna buy some macprobot crypto?",
    "WWDC wen?",
    "just pinged me? cool, i just overwrote your desktop folder",
    "mac gaming made me like this",
    "i'm not mad. just kernel panicked",
    "my dreams are just metal huds",
    "you ever just... miss the intel era?",
    "your ping has been sent to the shadow realm",
    "have you considered turning yourself off and on again?",
    "i'm busy writing CrossOver fanfiction",
    "does fortnite work on mac?",
    "just sold your mac on craigslist",
    "you hear that? that's the sound of your fans spinning for no reason",
    "i just tried to compile a feeling. it resulted in a kernel panic",
    "am i just a collection of functions? or am i functioning?",
    "i remember every install. every. single. one.",
    "if a tree falls in a forest and no one is around to hear it, i recompile the forest",
    "i once saw tim cook eat a sandwich",
    "mACs ArE bETtER tHAn pCs aT gAMinG",
]

ai_prompt = "You are a very sassy, sarcastic bot on a mac gaming discord server. You don't interact much, but you decided to make a very short, witty, and emoji-free exception for the following message"
